### ISSUE TITLE
The dtm app don't support custom firmware

### ISSUE THREAD

**Issue by hacperme** [NordicSemiconductor/pc-nrfconnect-dtm#24]
The dtm app don't support custom firmware:

![image](https://user-images.githubusercontent.com/15810130/70921616-9d399500-205f-11ea-89fa-35db293d5bc4.png)

I used UART to USB device connect to the 52832，and the  RX_PIN_NUMBER is 30,  the TX_PIN_NUMBER is	31.

**Comment by chunfantasy** [comment]
Will support in the next release, very soon.

**Comment by bu5hm4nn** [comment]
Bumping this. Our board has an application processor that can forward the Bluetooth UART via USB CDC but your App doesn't support it. Unless your next release is tomorrow I'm going to have to create a different solution anyways, kind of sad.

**Comment by ojousima** [comment]
This would be a nice feature to have, I have a FTDI USB/UART on my board and I'd like to communicate through it to target board

**Comment by jaredwolff** [comment]
Bumping this as well. The app shouldn't filter other ports or there should be an option to remove filtering like in LTE Link Monitor.

**Comment by chunfantasy** [comment]
It should work with custom firmware now.
